type: masif_gnn_regressor
attention: False

masif:
    use_mash: False
    embedding_layer: dMaSIF
    geometric_params:
        resolution:
        curvature_scales:
            - 1.0
            - 2.0
            - 3.0
            - 5.0
            - 10.0
        distance: 1.05
        variance: 0.1
        sup_sampling: 10
    embedding:
        atom_dims: 6
        emb_dims: 32
        in_channels: 16
        orientation_units: 16
        unet_hidden_channels: 8
        post_units: 8
        n_layers: 1
        radius: 9.0
        k: 40
        dropout: 0.0
        pocket_threshold: 20.0
    no_chem: False
    no_geom: False
    random_rotation: False
    search: False
    site: True

ligand_encoder:
    layers:
        - gcn
        - gcn
        - gcn
        - linear
    layer_dims:
        - 16
        - 16
        - 16 
        - 32
    layer_norm:
        - True
        - True
        - False
    batch_norm:
        - False
        - False
        - False
    activations: 
        - relu
        - relu
        - relu

classifier:
    layer_dims:
        - 64
        - 64
        - 1
    activations: 
        - relu
        - relu
        - none
    layer_norm:
        - True
        - True
    batch_norm:
        - False
        - False
    dropout: 0.0

loss:
    type: mse
    label_smoothing: 0.0
    