defaults:
    - dataset: pdb_bind
    - model: masif_gnn_regressor
    
params:
    task: train
    device: cpu
    num_gpus: 2
    precision: mixed 
    seed: 42
    max_runtime_mins: 10
    max_epochs: 10

dataloader:
    cached: False
    batch_size: 128
    batch_type: item
    shuffle: True
    data_usage_ratio: 1.0
    multi_process_count: 0
    multi_process_max_pre_fetch: 2

features:
    preprocessing:
        - protein
        - identity
        - ligand
        - identity
    representation:
        - protein
        - masif
        - ligand
        - mol_graph

optimiser:
    type: adam
    beta1: 0.9
    bet2: 0.999
    epsilon: 0.000000009
    learning_rate: 0.0001
    weight_decay: 0.0
    amsgrad: False